import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createFileRoute } from "@tanstack/react-router";
import { PRODUCTS, CATEGORIES, finalPrice } from "@/data/products";
import { DollarSign, ShoppingBag, Users, Package, Plus, TrendingUp, BarChart3 } from "lucide-react";
export const Route = createFileRoute("/admin")({
    head: () => ({ meta: [{ title: "Admin — BuyBee" }] }),
    component: Admin,
});
function Admin() {
    const revenue = 128432.5;
    const orders = 2341;
    const customers = 18422;
    const inventory = PRODUCTS.reduce((n, p) => n + p.stock, 0);
    return (_jsxs("div", { className: "mx-auto max-w-7xl px-4 py-8 md:px-6", children: [_jsxs("div", { className: "flex flex-wrap items-end justify-between gap-3", children: [_jsxs("div", { children: [_jsx("div", { className: "text-xs font-bold uppercase tracking-widest text-honey-deep", children: "BuyBee Console" }), _jsx("h1", { className: "font-display text-4xl font-bold", children: "Admin dashboard" })] }), _jsxs("button", { className: "inline-flex items-center gap-2 rounded-full gradient-honey px-4 py-2 text-sm font-bold text-ink shadow-honey", children: [_jsx(Plus, { className: "h-4 w-4" }), " Add product"] })] }), _jsxs("div", { className: "mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4", children: [_jsx(Stat, { icon: DollarSign, label: "Revenue", val: `$${revenue.toLocaleString()}`, trend: "+12.4%" }), _jsx(Stat, { icon: ShoppingBag, label: "Orders", val: orders.toLocaleString(), trend: "+6.1%" }), _jsx(Stat, { icon: Users, label: "Customers", val: customers.toLocaleString(), trend: "+8.9%" }), _jsx(Stat, { icon: Package, label: "Inventory", val: inventory.toLocaleString(), trend: "-2.1%" })] }), _jsxs("div", { className: "mt-8 grid gap-6 lg:grid-cols-[1fr_360px]", children: [_jsxs("div", { className: "glass rounded-3xl p-6 shadow-honey", children: [_jsxs("div", { className: "mb-4 flex items-center justify-between", children: [_jsx("h2", { className: "font-display text-lg font-bold", children: "Sales this week" }), _jsx(BarChart3, { className: "h-4 w-4 text-muted-foreground" })] }), _jsx(SparkBars, {}), _jsxs("div", { className: "mt-6 flex items-center justify-between text-xs text-muted-foreground", children: [_jsx("span", { children: "Mon" }), _jsx("span", { children: "Tue" }), _jsx("span", { children: "Wed" }), _jsx("span", { children: "Thu" }), _jsx("span", { children: "Fri" }), _jsx("span", { children: "Sat" }), _jsx("span", { children: "Sun" })] })] }), _jsxs("div", { className: "glass rounded-3xl p-6 shadow-honey", children: [_jsx("h2", { className: "mb-4 font-display text-lg font-bold", children: "Top categories" }), _jsx("div", { className: "space-y-3", children: CATEGORIES.slice(0, 6).map((c, i) => {
                                    const share = 80 - i * 10;
                                    return (_jsxs("div", { children: [_jsxs("div", { className: "mb-1 flex justify-between text-xs", children: [_jsx("span", { className: "font-semibold", children: c.name }), _jsxs("span", { className: "text-muted-foreground", children: [share, "%"] })] }), _jsx("div", { className: "h-2 overflow-hidden rounded-full bg-muted", children: _jsx("div", { className: "h-full gradient-honey", style: { width: `${share}%` } }) })] }, c.slug));
                                }) })] })] }), _jsxs("div", { className: "mt-8 glass rounded-3xl p-6 shadow-honey", children: [_jsxs("div", { className: "mb-4 flex items-center justify-between", children: [_jsx("h2", { className: "font-display text-lg font-bold", children: "Recent products" }), _jsx("button", { className: "text-xs font-semibold text-honey-deep", children: "View all" })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { className: "text-left text-xs uppercase text-muted-foreground", children: _jsxs("tr", { children: [_jsx("th", { className: "py-2", children: "Product" }), _jsx("th", { children: "Category" }), _jsx("th", { children: "Price" }), _jsx("th", { children: "Stock" }), _jsx("th", { children: "Status" }), _jsx("th", {})] }) }), _jsx("tbody", { children: PRODUCTS.slice(0, 8).map(p => (_jsxs("tr", { className: "border-t border-border", children: [_jsx("td", { className: "py-3", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("img", { src: p.images[0], alt: "", className: "h-10 w-10 rounded-lg object-cover" }), _jsxs("div", { children: [_jsx("div", { className: "font-semibold", children: p.name }), _jsx("div", { className: "text-xs text-muted-foreground", children: p.brand })] })] }) }), _jsx("td", { className: "capitalize", children: p.category.replace(/-/g, " ") }), _jsxs("td", { className: "font-semibold", children: ["$", finalPrice(p).toFixed(2)] }), _jsx("td", { children: p.stock }), _jsx("td", { children: _jsx("span", { className: `rounded-full px-2 py-0.5 text-xs font-semibold ${p.stock > 20 ? "bg-primary/20 text-honey-deep" : p.stock > 0 ? "bg-secondary/20 text-secondary" : "bg-destructive/10 text-destructive"}`, children: p.stock > 20 ? "In stock" : p.stock > 0 ? "Low" : "Out" }) }), _jsx("td", { className: "text-right", children: _jsx("button", { className: "text-xs font-semibold text-honey-deep", children: "Edit" }) })] }, p.id))) })] }) })] })] }));
}
function Stat({ icon: I, label, val, trend }) {
    const up = trend.startsWith("+");
    return (_jsxs("div", { className: "glass rounded-3xl p-5 shadow-honey", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "grid h-10 w-10 place-items-center rounded-2xl gradient-honey text-ink", children: _jsx(I, { className: "h-4 w-4" }) }), _jsxs("span", { className: `inline-flex items-center gap-1 text-xs font-bold ${up ? "text-honey-deep" : "text-destructive"}`, children: [_jsx(TrendingUp, { className: "h-3 w-3" }), " ", trend] })] }), _jsx("div", { className: "mt-4 font-display text-2xl font-bold", children: val }), _jsx("div", { className: "text-xs text-muted-foreground", children: label })] }));
}
function SparkBars() {
    const bars = [40, 62, 55, 78, 48, 90, 72];
    return (_jsx("div", { className: "flex h-40 items-end gap-3", children: bars.map((h, i) => (_jsx("div", { className: "flex-1 overflow-hidden rounded-t-xl gradient-honey shadow-honey", style: { height: `${h}%` } }, i))) }));
}
