import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "@tanstack/react-router";
import { Heart, Star, ShoppingBag } from "lucide-react";
import { finalPrice } from "@/data/products";
import { useStore } from "@/context/StoreContext";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
export function ProductCard({ product, className }) {
    const { toggleWish, state, addToCart } = useStore();
    const wished = state.wishlist.includes(product.id);
    const fp = finalPrice(product);
    return (_jsxs("div", { className: cn("group relative overflow-hidden rounded-3xl border border-border/60 bg-card p-3 shadow-honey transition duration-300 hover:-translate-y-1 hover:shadow-glow-honey", className), children: [_jsx(Link, { to: "/product/$id", params: { id: product.id }, className: "block", children: _jsxs("div", { className: "relative aspect-[4/5] overflow-hidden rounded-2xl bg-amber-soft", children: [_jsx("img", { src: product.images[0], alt: product.name, loading: "lazy", className: "h-full w-full object-cover transition duration-700 group-hover:scale-110" }), product.discount > 0 && (_jsxs("div", { className: "absolute left-3 top-3 rounded-full bg-secondary px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-secondary-foreground shadow", children: ["-", product.discount, "%"] })), product.tags?.includes("new") && (_jsx("div", { className: "absolute right-3 top-3 rounded-full bg-primary px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-primary-foreground shadow", children: "New" })), _jsx("button", { onClick: (e) => { e.preventDefault(); toggleWish(product.id); toast(wished ? "Removed from wishlist" : "Saved to wishlist 🐝"); }, "aria-label": "Toggle wishlist", className: "absolute bottom-3 right-3 grid h-9 w-9 place-items-center rounded-full bg-card/90 backdrop-blur shadow-honey transition hover:scale-110", children: _jsx(Heart, { className: cn("h-4 w-4", wished ? "fill-secondary text-secondary" : "text-ink") }) })] }) }), _jsxs("div", { className: "p-2 pt-3", children: [_jsxs("div", { className: "mb-1 flex items-center justify-between gap-2", children: [_jsx("div", { className: "text-[10px] font-semibold uppercase tracking-wider text-honey-deep", children: product.brand }), _jsxs("div", { className: "flex items-center gap-0.5 text-xs text-muted-foreground", children: [_jsx(Star, { className: "h-3 w-3 fill-primary text-primary" }), " ", product.rating] })] }), _jsx(Link, { to: "/product/$id", params: { id: product.id }, className: "line-clamp-2 min-h-10 text-sm font-medium leading-tight hover:text-honey-deep", children: product.name }), _jsxs("div", { className: "mt-3 flex items-end justify-between gap-2", children: [_jsxs("div", { className: "flex items-baseline gap-2", children: [_jsxs("div", { className: "text-lg font-bold text-ink", children: ["$", fp.toFixed(2)] }), product.discount > 0 && (_jsxs("div", { className: "text-xs text-muted-foreground line-through", children: ["$", product.price.toFixed(2)] }))] }), _jsx("button", { onClick: () => { addToCart(product.id, 1); toast.success(`Added ${product.name} to cart`); }, "aria-label": "Add to cart", className: "grid h-9 w-9 shrink-0 place-items-center rounded-full gradient-honey text-ink shadow-honey transition hover:scale-110", children: _jsx(ShoppingBag, { className: "h-4 w-4" }) })] })] })] }));
}
