/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as WishlistRouteImport } from './routes/wishlist';
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml';
import { Route as ShopRouteImport } from './routes/shop';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as LoginRouteImport } from './routes/login';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as FaqRouteImport } from './routes/faq';
import { Route as DealsRouteImport } from './routes/deals';
import { Route as ContactRouteImport } from './routes/contact';
import { Route as CheckoutRouteImport } from './routes/checkout';
import { Route as CartRouteImport } from './routes/cart';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as AccountRouteImport } from './routes/account';
import { Route as AboutRouteImport } from './routes/about';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ProductIdRouteImport } from './routes/product.$id';
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success';
import { Route as CategorySlugRouteImport } from './routes/category.$slug';
const WishlistRoute = WishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => rootRouteImport,
});
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => rootRouteImport,
});
const ShopRoute = ShopRouteImport.update({
    id: '/shop',
    path: '/shop',
    getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
});
const FaqRoute = FaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => rootRouteImport,
});
const DealsRoute = DealsRouteImport.update({
    id: '/deals',
    path: '/deals',
    getParentRoute: () => rootRouteImport,
});
const ContactRoute = ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => rootRouteImport,
});
const CheckoutRoute = CheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => rootRouteImport,
});
const CartRoute = CartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
});
const AccountRoute = AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => rootRouteImport,
});
const AboutRoute = AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const ProductIdRoute = ProductIdRouteImport.update({
    id: '/product/$id',
    path: '/product/$id',
    getParentRoute: () => rootRouteImport,
});
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => CheckoutRoute,
});
const CategorySlugRoute = CategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => rootRouteImport,
});
const CheckoutRouteChildren = {
    CheckoutSuccessRoute: CheckoutSuccessRoute,
};
const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(CheckoutRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AboutRoute: AboutRoute,
    AccountRoute: AccountRoute,
    AdminRoute: AdminRoute,
    CartRoute: CartRoute,
    CheckoutRoute: CheckoutRouteWithChildren,
    ContactRoute: ContactRoute,
    DealsRoute: DealsRoute,
    FaqRoute: FaqRoute,
    ForgotPasswordRoute: ForgotPasswordRoute,
    LoginRoute: LoginRoute,
    RegisterRoute: RegisterRoute,
    ShopRoute: ShopRoute,
    SitemapDotxmlRoute: SitemapDotxmlRoute,
    WishlistRoute: WishlistRoute,
    CategorySlugRoute: CategorySlugRoute,
    ProductIdRoute: ProductIdRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
